[Robot-Body-Isaac]
"1.0.0" = {features = [
    {"FET001_BASE_NEUTRAL" = {version = "0.1.0"}}, # "Minimal"
    {"FET004_ROBOT_PHYSX" = {version = "0.2.0"}}, # "Simulate Multi-Body Physics and SDF collision approximation"
    {"FET021_ROBOT_CORE_ISAAC" = {version = "0.2.0"}}, # "Robot Core Isaac"
    {"FET022_DRIVEN_JOINTS_ISAAC" = {version = "0.1.0"}}, # "Isaac Driven Joints
    {"FET024_BASE_ARTICULATION_PHYSX" = {version = "0.1.0"}}, # "Isaac Base Articulation"
    {"FET100_BASE_ISAACSIM" = {version = "0.1.0"}}, # "Isaac composition
]}
"1.1.0" = {features = [ # Deprecate RB.006
    {"FET001_BASE_NEUTRAL" = {version = "0.1.0"}}, # "Minimal"
    {"FET004_ROBOT_PHYSX" = {version = "0.3.0"}}, # "Simulate Multi-Body Physics and SDF collision approximation"
    {"FET021_ROBOT_CORE_ISAAC" = {version = "0.2.0"}}, # "Robot Core Isaac"
    {"FET022_DRIVEN_JOINTS_ISAAC" = {version = "0.2.0"}}, # "Isaac Driven Joints
    {"FET024_BASE_ARTICULATION_PHYSX" = {version = "0.1.0"}}, # "Isaac Base Articulation"
    {"FET100_BASE_ISAACSIM" = {version = "0.2.0"}}, # "Isaac composition
]}
